export const lookupsDocSourceType =
	[
		{
			DOC_SOURCE_ID: '1',
			SOURCE_DESC: 'GEN Office (IN)',
			SOURCE_DESC_AR: 'سجل الوارد العام',
			ABBR_AR: 'ر',
			CABINETID: '11601',
			ACL_RESOURCE_NAME: 'DOC.GENERALOFFICE',
			ACTIVE: '1',
			LONG_DESC: 'NULL',
			LONG_DESC_AR: 'NULL',
			SPL_ACL_RESOURCE: 'NULL',
			LOCATE: 'NULL',
			ACL_LINK_RESOURCE: 'NULL',
			SPL_EDITOR_RESOURCE: 'NULL',
			READ_ONLY: 'NULL'
		},
		{
			DOC_SOURCE_ID: '1',
			SOURCE_DESC: 'INTL Office (IN)',
			SOURCE_DESC_AR: 'سجل المعاملة الداخلية',
			ABBR_AR: 'ر',
			CABINETID: '11603',
			ACL_RESOURCE_NAME: 'DOC.INTERNALOFFICE',
			ACTIVE: '1',
			LONG_DESC: 'NULL',
			LONG_DESC_AR: 'NULL',
			SPL_ACL_RESOURCE: 'NULL',
			LOCATE: 'NULL',
			ACL_LINK_RESOURCE: 'NULL',
			SPL_EDITOR_RESOURCE: 'NULL',
			READ_ONLY: 'NULL'
		}
	];
